config:
  default: true
  MD013: false
  MD026:
    punctuation: '.,;:!'
  MD029:
    style: ordered
  MD033: false
  MD034: false
  MD041: false
  MD051: false
ignores:
  - CHANGELOG.md
  - "{,docs/}{RELEASE,release}.md"
  - docs/about/release/release_notes.md
  - tools/autotag/templates/**/*.md
