# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

sphinx:
   configuration: docs/conf.py

formats: [htmlzip]

python:
   install:
   - requirements: docs/.sphinx/requirements.txt

build:
   os: "ubuntu-20.04"
   tools:
      python: "3.8"
   jobs:
      pre_build:
         - python -m sphinx -b linkcheck -D linkcheck_timeout=1 docs/ _build/linkcheck
