matrix:
- name: Markdown
  sources:
  - ['tools/autotag/templates/**/*.md', '!tools/autotag/templates/**/5*.md', '!tools/autotag/templates/**/6.0*.md', '!tools/autotag/templates/**/6.1*.md']
- name: reST
  sources:
  - []
- name: Cpp
  sources:
  - []
