variables:
- group: common
- template: /.azuredevops/variables-global.yml

parameters:
- name: checkoutRef
  type: string
  default: refs/tags/v3.9.1

resources:
  repositories:
  - repository: pipelines_repo
    type: github
    endpoint: ROCm
    name: ROCm/ROCm
  - repository: release_repo
    type: github
    endpoint: Reference-LAPACK
    name: Reference-LAPACK/lapack
    ref: ${{ parameters.checkoutRef }}

trigger: none
pr: none

jobs:
  - template: ${{ variables.CI_COMPONENT_PATH }}/lapack.yml
    parameters:
      checkoutRepo: release_repo
      checkoutRef: ${{ parameters.checkoutRef }}
