parameters:
- name: checkoutRepo
  type: string
  default: 'self'
- name: checkoutRef
  type: string
  default: ''
- name: aptPackages
  type: object
  default:
    - gfortran
    - git
    - cmake
    - rocm-cmake
    - clang
jobs:
- job: amdmigraphx
  timeoutInMinutes: 180
  variables:
  - group: common
  - template: /.azuredevops/variables-global.yml
  pool: ${{ variables.HIGH_END_BUILD_POOL }}
  container:
    image: ${{ variables.DOCKER_IMAGE_NAME }}:${{ variables.LATEST_DOCKER_VERSION }}
  workspace:
    clean: all
  steps:
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/dependencies.yml
    parameters:
      aptPackages: ${{ parameters.aptPackages }}
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/preamble.yml
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/checkout.yml
    parameters:
      checkoutRepo: ${{ parameters.checkoutRepo }}
  - script: mkdir prereqs
  - script: prereqs_dir=$'prereqs'
  - script: sudo ./tools/install_prereqs.sh $prereqs_dir
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/build-cmake.yml
    parameters:
      extraBuildFlags: >-
        -DCMAKE_CXX_COMPILER=hipcc
        -DAMDGPU_TARGETS=gfx1100
        -DCMAKE_PREFIX_PATH=$your_loc=$prereqs_dir
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/artifact-upload.yml
