parameters:
- name: checkoutRepo
  type: string
  default: 'self'
- name: checkoutRef
  type: string
  default: ''
- name: aptPackages
  type: object
  default:
    - git
    - cmake
    - ninja-build
    - libnuma-dev
    - miopen-hip-dev
    - openmp-extras
    - python3-venv
    - rocblas-dev
    - libtbb-dev
    - half
    - nlohmann-json3-dev
    - libmsgpack-dev
    - libsqlite3-dev
    - libprotobuf-dev
    - protobuf-compiler
    - python3-pybind11
    - composablekernel-dev
    - rocmlir-dev
- name: pipModules
  type: object
  default:
    - https://github.com/RadeonOpenCompute/rbuild/archive/master.tar.gz
    - onnx==1.14.1
    - numpy==1.21.6
    - typing==3.7.4
    - pytest==6.0.1
    - packaging==23.0
    - protobuf==3.20.2

jobs:
- job: AMDMIGraphX
  variables:
  - group: common
  - template: /.azuredevops/variables-global.yml
  pool: ${{ variables.HIGH_END_BUILD_POOL }}
  container:
    image: ${{ variables.DOCKER_IMAGE_NAME }}:${{ variables.LATEST_DOCKER_VERSION }}
  workspace:
    clean: all
  steps:
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/dependencies.yml
    parameters:
      aptPackages: ${{ parameters.aptPackages }}
      pipModules: ${{ parameters.pipModules }}
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/preamble.yml
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/checkout.yml
    parameters:
      checkoutRepo: ${{ parameters.checkoutRepo }}
  - script: 'ls -1R /opt/rocm'
    displayName: 'Artifact listing'
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/build-cmake.yml
    parameters:
      extraBuildFlags: >-
        -DCMAKE_CXX_COMPILER=/opt/rocm/llvm/bin/clang++
        -DCMAKE_C_COMPILER=/opt/rocm/llvm/bin/clang
        -DCMAKE_PREFIX_PATH=/opt/rocm
        -DCMAKE_BUILD_TYPE=Release
        -DAMDGPU_TARGETS=gfx1100
        -DCMAKE_PREFIX_PATH=/opt/rocm/llvm;opt/rocm
        -DONNX_USE_PROTOBUF_SHARED_LIBS=ON
        -GNinja
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/artifact-upload.yml
