parameters:
- name: checkoutRepo
  type: string
  default: 'self'
- name: checkoutRef
  type: string
  default: ''
- name: aptPackages
  type: object
  default:
    - cmake
    - ninja-build
    - rocblas-dev
    - rocsparse
    - rocsolver-dev
    - gfortran
    - libopenblas-dev
    - googletest
    - git
    - libgtest-dev
    - libblis-dev
    - wget

jobs:
- job: hipBLAS
  variables:
  - group: common
  - template: /.azuredevops/variables-global.yml
  - name: LD_LIBRARY_PATH
    value: '/lib:/usr/lib:/usr/local/lib'
  pool: ${{ variables.MEDIUM_BUILD_POOL }}
  container:
    image: ${{ variables.DOCKER_IMAGE_NAME }}:${{ variables.LATEST_DOCKER_VERSION }}
  workspace:
    clean: all
  steps:
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/dependencies-other.yml
    parameters:
      aptPackages: ${{ parameters.aptPackages }}
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/preamble.yml
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/checkout.yml
    parameters:
      checkoutRepo: ${{ parameters.checkoutRepo }}
  - task: Bash@3
    displayName: 'Clone lapack'
    inputs:
      targetType: inline
      script: git clone --depth 1 --branch v3.9.1 https://github.com/Reference-LAPACK/lapack
      workingDirectory: '$(Build.SourcesDirectory)'
  - task: Bash@3
    displayName: 'Download AOCL'
    inputs:
      targetType: inline
      script: wget -nv https://download.amd.com/developer/eula/aocl/aocl-4-2/aocl-linux-aocc-4.2.0_1_amd64.deb
      workingDirectory: '$(Pipeline.Workspace)'
  - task: Bash@3
    displayName: 'Install AOCL'
    inputs:
      targetType: inline
      script: sudo apt install --yes ./aocl-linux-aocc-4.2.0_1_amd64.deb
      workingDirectory: '$(Pipeline.Workspace)'
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/build-cmake.yml
    parameters:
      componentName: lapack
      extraBuildFlags: >-
        -DBUILD_TESTING=OFF
        -DCBLAS=ON
        -DLAPACKE=OFF
        -GNinja
      cmakeBuildDir: '$(Build.SourcesDirectory)/lapack/build'
      installDir: '$(Pipeline.Workspace)/deps-install'
  - task: Bash@3
    displayName: 'Move lapack to /usr/local'
    inputs:
      targetType: inline
      script: sudo cp -r * /usr/local
      workingDirectory: '$(Pipeline.Workspace)/deps-install'
  - task: Bash@3
    displayName: 'ldconfig'
    inputs:
      targetType: inline
      script: sudo ldconfig
      workingDirectory: '/usr/local/lib'
  - script: 'ls -1R /usr/local'
    displayName: 'Artifact listing'
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/build-cmake.yml
    parameters:
      extraBuildFlags: >-
        -DCMAKE_PREFIX_PATH=/opt/rocm
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_CXX_COMPILER=/opt/rocm/llvm/bin/clang++
        -DAMDGPU_TARGETS=gfx1030;gfx1100
        -DHIP_PLATFORM=amd
        -DBUILD_CLIENTS_TESTS=ON
        -DBUILD_CLIENTS_BENCHMARKS=OFF
        -DBUILD_CLIENTS_SAMPLES=OFF
        -DCPACK_SET_DESTDIR=OFF
        -GNinja
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/artifact-upload.yml
