parameters:
- name: checkoutRepo
  type: string
  default: 'self'
- name: checkoutRef
  type: string
  default: ''
- name: aptPackages
  type: object
  default:
    - cmake
    - ninja-build
    - rocblas
    - rocsparse
    - hipsparse
    - rocsolver
    - libsuitesparse-dev
    - gfortran
    - git
    - googletest
    - libgtest-dev

jobs:
- job: hipSOLVER
  variables:
  - group: common
  - template: /.azuredevops/variables-global.yml
  pool:
    vmImage: ${{ variables.BASE_BUILD_POOL }}
  container:
    image: ${{ variables.DOCKER_IMAGE_NAME }}:${{ variables.LATEST_DOCKER_VERSION }}
  workspace:
    clean: all
  steps:
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/dependencies-other.yml
    parameters:
      aptPackages: ${{ parameters.aptPackages }}
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/preamble.yml
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/checkout.yml
    parameters:
      checkoutRepo: ${{ parameters.checkoutRepo }}
# build external gtest and lapack
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/build-cmake.yml
    parameters:
      componentName: external
      cmakeBuildDir: 'deps/build'
      installDir: '$(Pipeline.Workspace)/deps-install'
      extraBuildFlags: >-
        -DBUILD_BOOST=OFF
        -DBUILD_GTEST=OFF
        -GNinja
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/build-cmake.yml
    parameters:
      extraBuildFlags: >-
        -DCMAKE_PREFIX_PATH="/opt/rocm;$(Pipeline.Workspace)/deps-install"
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_CXX_COMPILER=/opt/rocm/bin/amdclang++
        -DCMAKE_C_COMPILER=/opt/rocm/bin/amdclang
        -DAMDGPU_TARGETS=gfx1030;gfx1100
        -DBUILD_CLIENTS_TESTS=ON
        -DUSE_CUDA=OFF
        -GNinja
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/artifact-upload.yml
