name: Linting

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  call-workflow-passing-data:
    name: Documentation Linting
    uses: RadeonOpenCompute/rocm-docs-core/.github/workflows/linting.yml@develop
