name: Linting

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  call-workflow-passing-data:
    name: Documentation
    uses: RadeonOpenCompute/rocm-docs-core/.github/workflows/linting.yml@develop
