
name: Markdownlint Action
on:
  push:
  pull_request:
    branches: [develop, main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Use markdownlint
      uses: actionshub/markdownlint@v3.1.3
      with:
        filesToIgnoreRegex: CHANGELOG.md
