
name: Markdownlint Action
on:
  push:
  pull_request:
    branches: [develop, main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Use markdownlint
      uses: actionshub/markdownlint@v3.1.3
      with:
        filesToIgnoreRegex: "CHANGELOG.md|CONTRIBUTING.md|README.md|
docs/packaging_guidelines.md|docs/about.md|docs/quick_start.md|docs/index.md|
docs/release/gpu_os_support.md|docs/how_to/magma_install/magma_install.md|
docs/reference/gpu_libraries/math.md|docs/reference/rocmcc/rocmcc.md|docs/reference/docker.md|docs/reference/hip.md|
docs/hip_sdk_install_win/hip_sdk_install_win.md|docs/all_deploy_options.md|
inception_casestudy.md|deep_learning_rocm.md|quick_start_windows.md|tensorflow_install.md|
pytorch_install.md|mi250.md|openmp.md|c++_primitives.md|ai_tools.md|computer_vision.md|all.md|compilers.md|
management_tools.md|validation_tools.md|installing_linux.md|file_reorg.md|prerequisites.md|
quick_start_linux.md|docker_support_matrix.md|gpu_os_support.md|"
